language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:beineri/opt-qt532
  - sudo apt-get update -qq
  - sudo apt-get -qq install g++-4.8
  - sudo apt-get install -qq qt53base qt53multimedia
  - sudo apt-get install -qq build-essential libjack-jackd2-dev libsamplerate0-dev libavformat-dev libavcodec-dev libavutil-dev libasound2-dev libboost-all-dev libfftw3-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - source /opt/qt53/bin/qt53-env.sh
  - qmake --version
  - git clone https://github.com/jrosener/libKeyFinder.git
  - cd libKeyFinder && qmake && make && sudo make install
script:
  - cd libdigitalscratch && qmake && make && sudo make install
  - make clean && qmake CONFIG+=test && make
  - ./libdigitalscratch-test
  - cd ../digitalscratch && qmake && make
  - make clean && qmake CONFIG+=test-no_device_test && make
  - ./digitalscratch-test
