language: cpp
compiler: gcc
before_install: sudo apt-get update
install: sudo apt-get install build-essential qt5-default
script: cd libdigitalscratch && qmake CONFIG+=test && make && ./libdigitalscratch-test
