language: cpp
compiler: gcc
before_install:
  - sudo apt-add-repository -y ppa:julien-rosener/digitalscratch
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential qt-sdk libkeyfinder-dev libjack-jackd2-dev libsamplerate0-dev libavformat-dev libavcodec-dev libavutil-dev
script:
  - cd libdigitalscratch
  - qmake CONFIG+=test
  - make
  - ./libdigitalscratch-test
  - make clean
  - qmake
  - make
  - sudo make install
  - cd ../digitalscratch
  - qmake CONFIG+=test
  - make
  - ./digitalscratch-test
