language: cpp
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential qt-sdk libjack-jackd2-dev libsamplerate0-dev libkeyfinder-dev libavformat-dev libavcodec-dev libavutil-dev
script:
  - cd libdigitalscratch
  - qmake CONFIG+=test
  - make
  - ./libdigitalscratch-test
